export const Z_INDEX = {
  HEADER: 100,
  POPPER: 100,
  PAGE_LOADER: 1000,
  MENU_ARROW: 100,
}

export enum ERRORS {
  ANAUTHORIZED = 'ANAUTHORIZED',
  NOT_FOUND = 'NOT FOUND',
  DEFAULT = 'DEFAULT',
}
