import React from 'react'
import ThemeRegistry from '../components/Theme/ThemeRegistry/ThemeRegistry'
import StoreProvider from '../store/StoreProvider'
import AuthLayout from '../components/layouts/AuthLayout'
import SnackBarProvider from '../components/Providers/SnackBarProvider'

import '../styles/_global.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <ThemeRegistry>
            <SnackBarProvider>
              <AuthLayout>
                <main>{children}</main>
              </AuthLayout>
            </SnackBarProvider>
          </ThemeRegistry>
        </StoreProvider>
      </body>
    </html>
  )
}
